### ISSUE TITLE
#1 - Replace SC4K with Splunk OpenTelemetry Collector for Kubernetes

### ISSUE THREAD

**Issue by klawrencegupta-splunk** [splunk/sdds#1]
Splunk Connnect for Kubernetes is deprecated and replaced with Splunk OpenTelemetry Collector for Kubernetes (https://github.com/signalfx/splunk-otel-collector-chart)

**Comment by klawrencegupta-splunk** [comment]
EKS Customer running into error with the staging README file in deployment-apps while building a second node

```
splunk_common : Start Splunk via CLI ----------------------------------- 21.62s
splunk_common : Update Splunk directory owner --------------------------- 1.79s
splunk_common : Get Splunk status --------------------------------------- 1.74s
Gathering Facts --------------------------------------------------------- 1.52s
splunk_common : Update /opt/splunk/etc ---------------------------------- 1.22s
Running /sbin/updateetc.sh
Error version: deployment-apps/README: Cannot open: File Exists
Exiting with failure status due to previous error
```
Suggested Workaround:
Add a remove file command to the postStart lifecycle yaml to delete the file and resolve the conflict

```
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 120s; sudo /opt/splunk/bin/./splunk enable deploy-server -auth admin:changeme123; rm -f /opt/splunk/etc/deployment-apps/README"]
```
