### ISSUE TITLE
#2 - EKS Customer has reported a conflict with the staging README file set during the Splunk container build

### ISSUE THREAD

**Issue by klawrencegupta-splunk** [splunk/sdds#2]
EKS Customer has reported a conflict with the staging README file set during the Splunk container build
```
splunk_common : Start Splunk via CLI ----------------------------------- 21.62s
splunk_common : Update Splunk directory owner --------------------------- 1.79s
splunk_common : Get Splunk status --------------------------------------- 1.74s
Gathering Facts --------------------------------------------------------- 1.52s
splunk_common : Update /opt/splunk/etc ---------------------------------- 1.22s
Running /sbin/updateetc.sh
Error version: deployment-apps/README: Cannot open: File Exists
Exiting with failure status due to previous error
```

**Suggested Workaround**

Add a remove README command to the postStart lifecycle process; this should resolve the conflict and allow the build to continue

```
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 120s; sudo /opt/splunk/bin/./splunk enable deploy-server -auth admin:changeme123; rm -f /opt/splunk/etc/deployment-apps/README"]

```
