### ISSUE TITLE
401 Errors from UFs - unable to download apps

### ISSUE THREAD

**Issue by klawrencegupta-splunk** [splunk/sdds#4]
401 errors can be thrown on the UF if the pass4SymmKey generated by the default SDDS build doesn't match the pass4SymmKey already used in production. 

To set a pass4SymmKey for the DS use the provided optional-server.conf file along with the provided restmap.conf to set the value for the containers running DS

```
 [deployment]
 pass4SymmKey = <one set in production>
```

**Comment by DevAlphaKilo** [comment]
Hi @klawrencegupta-splunk, the described solution above does not account for different replicas containing different `splunk.secret` files, generated randomly when the server starts, leading to only one of the three initial pods being able to decrypt the **pass4SymmKey** key value and causing continued 401 errors for the UF when communicating with the other two pods.

Upon startup whichever pod is able to encrypt the **pass4SymmKey** key value into `/opt/splunk/etc/apps/sdds_global_config/local/server.conf` first is the only pod that is able to communicate successfully with the UFs. Additionally, Once the pods are scaled to 0 and back to desired count (reloaded) no pods are able to decrypt the **pass4SymmKey** as the `splunk.secret` file has been regenerated and all communication with UFs result in further 401 errors. This forces admins to delete the `/opt/splunk/etc/apps/sdds_global_config/local/server.conf` file from the server (or repo preferably) and reload the pods again starting the race condition cycle all over again. 

To accomplish the described solution I seeded the **SPLUNK_SECRET** environment variable with a randomly generated string across all pods so they all have the same `$SPLUNK_HOME/etc/auth/splunk.secret` file on the filesystem. This allows all pods to decrypt the **pass4SymmKey** key value located in `/opt/splunk/etc/apps/sdds_global_config/local/server.conf` with the initial deployment and subsequent pods generated during the reload process. Example below.

**sdds.yaml**
```yaml
env:
  - name: SPLUNK_HOME
    value: /opt/splunk
  - name: SPLUNK_ETC
    value: /opt/splunk/etc
  - name: SPLUNK_PASSWORD
    value: changeme123
  - name: SPLUNK_START_ARGS
    value: "--accept-license --no-prompt --answer-yes"
  # Required so all replicas can decrypt encrypted values
  - name: SPLUNK_SECRET
    value: super-secret-key
```

As an alternative solution, I have seeded the **SPLUNK_PASS4SYMMKEY** environment variable with the **pass4SymmKey** key value expected for UF communication and updated the `/opt/splunk/etc/apps/sdds_global_config/default/restmap.conf` (in the repo) to target the `[general]` stanza. Example below.

**sdds.yaml**
```yaml
env:
  - name: SPLUNK_HOME
    value: /opt/splunk
  - name: SPLUNK_ETC
    value: /opt/splunk/etc
  - name: SPLUNK_PASSWORD
    value: changeme123
  - name: SPLUNK_START_ARGS
    value: "--accept-license --no-prompt --answer-yes"
  # Need to update restmap.conf to target [general] if used
  - name: SPLUNK_PASS4SYMMKEY
    value: super-secret-key  
```

**restmap.conf**
```ini
#restmap.conf required for 9.0
[streams:deployment]
requireAuthentication=true
authKeyStanza=general
```

I have also opened https://github.com/splunk/docker-splunk/issues/702 to request support for environment variable based configuration of the **pass4SymmKey** in the `[deployment]` stanza which would simplify this second solution by generating your initially prescribed solution in the `$SPLUNK_HOME/etc/system/local/server.conf` file in the pods and eliminating the need to update `restmap.conf` to use `[general]` while accounting for the different `splunk.secret` files per pod. 

Where as both solutions seem to work, I prefer to use your initially prescribed solution with the addition of the first fix I described to maintain using the `[deployment]` stanza specific **pass4SymmKey** key for the Deployment Servers.
